### PR TITLE
Optimize for rustc 1.20+ which can match ident faster

### PR DESCRIPTION
**Pull request by dtolnay**
This performs about 10% better on my machine: the included benchmark is down from 160 microseconds to 144 microseconds.

Mentioning @nnethercote regarding https://github.com/alexcrichton/proc-macro2/pull/94#issuecomment-452512128 -- would you like to try this commit in the rustc-perf benchmark before merging?

### CODE REVIEW

**Comment by mystor** [comment]
If we're up for optimizing for more recent versions this way, I wonder if we should implement quote! as a proc macro on sufficiently recent versions for perf.

**Comment by dtolnay** [comment]
I would welcome a PR that implements quote as a proc macro to benchmark against.

**Comment by dtolnay** [comment]
Abandoning because I would prefer not to land this more complicated implementation in the absence of rustc-perf numbers measuring an improvement.

**Comment by nnethercote** [comment]
@dtolnay: I apologize for not responding to this back in January. I just tried the patch but it has bitrotted. Would you be able to create a new version? I will be able to benchmark it against rustc-perf if you do. Thanks.

**Comment by dtolnay** [comment]
@nnethercote sure thing, here's the PR: https://github.com/dtolnay/quote/pull/135

**Pull request closed without merging**
